namespace Workhub.Contracts.Profileing;
public record MyProfileResponse(string FirstName,
 string LastName,
 string Email,
 string PhoneNumber,
 byte[] ProfileImage,
 string Country,
 string Address,
 string State,
 string Occupation,
 string Gender,
 string Experience,
 int Rating,
 int JobCount,
 string Token,
 string Id,
 string LongLat,
 string UserType);