<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Authentication\Commands\**" />
    <Compile Remove="Authentication\Common\**" />
    <Compile Remove="Authentication\Queries\**" />
    <EmbeddedResource Remove="Authentication\Commands\**" />
    <EmbeddedResource Remove="Authentication\Common\**" />
    <EmbeddedResource Remove="Authentication\Queries\**" />
    <None Remove="Authentication\Commands\**" />
    <None Remove="Authentication\Common\**" />
    <None Remove="Authentication\Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.27.8" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Workhub.Domain\Workhub.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Profiless\Commands\" />
  </ItemGroup>

</Project>
